//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Renamer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7852_2-R-014_069_000-SES-01")]
        public string search1 {
            get {
                return ((string)(this["search1"]));
            }
            set {
                this["search1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7852_2-R-014_069_000-SES-01")]
        public string replace1 {
            get {
                return ((string)(this["replace1"]));
            }
            set {
                this["replace1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7852/2-Р-014.069.000-СЭС-01")]
        public string search2 {
            get {
                return ((string)(this["search2"]));
            }
            set {
                this["search2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7852/2-Р-014.069.000-СЭС-01")]
        public string replace2 {
            get {
                return ((string)(this["replace2"]));
            }
            set {
                this["replace2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Обустройство кустовой площадки №15.3 Северо-Комсомольского месторождения. Этапы 5" +
            "-41")]
        public string search3 {
            get {
                return ((string)(this["search3"]));
            }
            set {
                this["search3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Обустройство кустовой площадки №15.3 Северо-Комсомольского месторождения. Этапы 5" +
            "-41")]
        public string replace3 {
            get {
                return ((string)(this["replace3"]));
            }
            set {
                this["replace3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Обустройство кустовой площадки №15.3")]
        public string search4 {
            get {
                return ((string)(this["search4"]));
            }
            set {
                this["search4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Обустройство кустовой площадки №15.3")]
        public string replace4 {
            get {
                return ((string)(this["replace4"]));
            }
            set {
                this["replace4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("432219")]
        public string search5 {
            get {
                return ((string)(this["search5"]));
            }
            set {
                this["search5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("432219")]
        public string replace5 {
            get {
                return ((string)(this["replace5"]));
            }
            set {
                this["replace5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25.08.22")]
        public string search6 {
            get {
                return ((string)(this["search6"]));
            }
            set {
                this["search6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25.08.22")]
        public string replace6 {
            get {
                return ((string)(this["replace6"]));
            }
            set {
                this["replace6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7852/2")]
        public string search7 {
            get {
                return ((string)(this["search7"]));
            }
            set {
                this["search7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7852/2")]
        public string replace7 {
            get {
                return ((string)(this["replace7"]));
            }
            set {
                this["replace7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("014.069.000")]
        public string search8 {
            get {
                return ((string)(this["search8"]));
            }
            set {
                this["search8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("014.069.000")]
        public string replace8 {
            get {
                return ((string)(this["replace8"]));
            }
            set {
                this["replace8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string search9 {
            get {
                return ((string)(this["search9"]));
            }
            set {
                this["search9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string replace9 {
            get {
                return ((string)(this["replace9"]));
            }
            set {
                this["replace9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string search10 {
            get {
                return ((string)(this["search10"]));
            }
            set {
                this["search10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string replace10 {
            get {
                return ((string)(this["replace10"]));
            }
            set {
                this["replace10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool wildcard {
            get {
                return ((bool)(this["wildcard"]));
            }
            set {
                this["wildcard"] = value;
            }
        }
    }
}
